// flow-typed signature: 44bea27d5ef33c37bc577b96fe20845e
// flow-typed version: <<STUB>>/react-dev-utils-for-webpack4_v^5.0.0-webpack4/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dev-utils-for-webpack4'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dev-utils-for-webpack4' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dev-utils-for-webpack4/browsersHelper' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/checkRequiredFiles' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/clearConsole' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/crossSpawn' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/errorOverlayMiddleware' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/eslintFormatter' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/FileSizeReporter' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/formatWebpackMessages' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/getCSSModuleLocalIdent' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/getProcessForPort' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/ignoredFiles' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/inquirer' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/InterpolateHtmlPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/launchEditor' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/launchEditorEndpoint' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/ModuleScopePlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/noopServiceWorkerMiddleware' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/openBrowser' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/printBuildError' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/printHostingInstructions' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/WatchMissingNodeModulesPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/WebpackDevServerUtils' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/webpackHotDevClient' {
  declare module.exports: any;
}

declare module 'react-dev-utils-for-webpack4/workspaceUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dev-utils-for-webpack4/browsersHelper.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/browsersHelper'>;
}
declare module 'react-dev-utils-for-webpack4/checkRequiredFiles.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/checkRequiredFiles'>;
}
declare module 'react-dev-utils-for-webpack4/clearConsole.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/clearConsole'>;
}
declare module 'react-dev-utils-for-webpack4/crossSpawn.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/crossSpawn'>;
}
declare module 'react-dev-utils-for-webpack4/errorOverlayMiddleware.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/errorOverlayMiddleware'>;
}
declare module 'react-dev-utils-for-webpack4/eslintFormatter.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/eslintFormatter'>;
}
declare module 'react-dev-utils-for-webpack4/FileSizeReporter.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/FileSizeReporter'>;
}
declare module 'react-dev-utils-for-webpack4/formatWebpackMessages.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/formatWebpackMessages'>;
}
declare module 'react-dev-utils-for-webpack4/getCSSModuleLocalIdent.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/getCSSModuleLocalIdent'>;
}
declare module 'react-dev-utils-for-webpack4/getProcessForPort.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/getProcessForPort'>;
}
declare module 'react-dev-utils-for-webpack4/ignoredFiles.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/ignoredFiles'>;
}
declare module 'react-dev-utils-for-webpack4/inquirer.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/inquirer'>;
}
declare module 'react-dev-utils-for-webpack4/InterpolateHtmlPlugin.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/InterpolateHtmlPlugin'>;
}
declare module 'react-dev-utils-for-webpack4/launchEditor.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/launchEditor'>;
}
declare module 'react-dev-utils-for-webpack4/launchEditorEndpoint.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/launchEditorEndpoint'>;
}
declare module 'react-dev-utils-for-webpack4/ModuleScopePlugin.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/ModuleScopePlugin'>;
}
declare module 'react-dev-utils-for-webpack4/noopServiceWorkerMiddleware.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/noopServiceWorkerMiddleware'>;
}
declare module 'react-dev-utils-for-webpack4/openBrowser.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/openBrowser'>;
}
declare module 'react-dev-utils-for-webpack4/printBuildError.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/printBuildError'>;
}
declare module 'react-dev-utils-for-webpack4/printHostingInstructions.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/printHostingInstructions'>;
}
declare module 'react-dev-utils-for-webpack4/WatchMissingNodeModulesPlugin.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/WatchMissingNodeModulesPlugin'>;
}
declare module 'react-dev-utils-for-webpack4/WebpackDevServerUtils.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/WebpackDevServerUtils'>;
}
declare module 'react-dev-utils-for-webpack4/webpackHotDevClient.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/webpackHotDevClient'>;
}
declare module 'react-dev-utils-for-webpack4/workspaceUtils.js' {
  declare module.exports: $Exports<'react-dev-utils-for-webpack4/workspaceUtils'>;
}
